package com.qazit.sysmanager.web.model;

public class RolePermission extends RolePermissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.hospitalId
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    private String hospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.hospitalId
     *
     * @return the value of role_permission.hospitalId
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.hospitalId
     *
     * @param hospitalId the value for role_permission.hospitalId
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }
}