package com.qazit.sysmanager.web.model;

public class TMemDicnPara {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.para_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private Long paraId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.dicn_type_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private Long dicnTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.dicn_type_code
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String dicnTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.para_name
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String paraName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.para_val
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String paraVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.para_desc
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String paraDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.if_default
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String ifDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.para_state
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String paraState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.para_sort
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private Integer paraSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.delete_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String deleteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEM_DICN_PARA.delete_data
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    private String deleteData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.para_id
     *
     * @return the value of T_MEM_DICN_PARA.para_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public Long getParaId() {
        return paraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.para_id
     *
     * @param paraId the value for T_MEM_DICN_PARA.para_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setParaId(Long paraId) {
        this.paraId = paraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.dicn_type_id
     *
     * @return the value of T_MEM_DICN_PARA.dicn_type_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public Long getDicnTypeId() {
        return dicnTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.dicn_type_id
     *
     * @param dicnTypeId the value for T_MEM_DICN_PARA.dicn_type_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setDicnTypeId(Long dicnTypeId) {
        this.dicnTypeId = dicnTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.dicn_type_code
     *
     * @return the value of T_MEM_DICN_PARA.dicn_type_code
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getDicnTypeCode() {
        return dicnTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.dicn_type_code
     *
     * @param dicnTypeCode the value for T_MEM_DICN_PARA.dicn_type_code
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setDicnTypeCode(String dicnTypeCode) {
        this.dicnTypeCode = dicnTypeCode == null ? null : dicnTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.para_name
     *
     * @return the value of T_MEM_DICN_PARA.para_name
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getParaName() {
        return paraName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.para_name
     *
     * @param paraName the value for T_MEM_DICN_PARA.para_name
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setParaName(String paraName) {
        this.paraName = paraName == null ? null : paraName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.para_val
     *
     * @return the value of T_MEM_DICN_PARA.para_val
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getParaVal() {
        return paraVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.para_val
     *
     * @param paraVal the value for T_MEM_DICN_PARA.para_val
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setParaVal(String paraVal) {
        this.paraVal = paraVal == null ? null : paraVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.para_desc
     *
     * @return the value of T_MEM_DICN_PARA.para_desc
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getParaDesc() {
        return paraDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.para_desc
     *
     * @param paraDesc the value for T_MEM_DICN_PARA.para_desc
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setParaDesc(String paraDesc) {
        this.paraDesc = paraDesc == null ? null : paraDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.if_default
     *
     * @return the value of T_MEM_DICN_PARA.if_default
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getIfDefault() {
        return ifDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.if_default
     *
     * @param ifDefault the value for T_MEM_DICN_PARA.if_default
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setIfDefault(String ifDefault) {
        this.ifDefault = ifDefault == null ? null : ifDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.para_state
     *
     * @return the value of T_MEM_DICN_PARA.para_state
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getParaState() {
        return paraState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.para_state
     *
     * @param paraState the value for T_MEM_DICN_PARA.para_state
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setParaState(String paraState) {
        this.paraState = paraState == null ? null : paraState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.para_sort
     *
     * @return the value of T_MEM_DICN_PARA.para_sort
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public Integer getParaSort() {
        return paraSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.para_sort
     *
     * @param paraSort the value for T_MEM_DICN_PARA.para_sort
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setParaSort(Integer paraSort) {
        this.paraSort = paraSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.delete_id
     *
     * @return the value of T_MEM_DICN_PARA.delete_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getDeleteId() {
        return deleteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.delete_id
     *
     * @param deleteId the value for T_MEM_DICN_PARA.delete_id
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setDeleteId(String deleteId) {
        this.deleteId = deleteId == null ? null : deleteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEM_DICN_PARA.delete_data
     *
     * @return the value of T_MEM_DICN_PARA.delete_data
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getDeleteData() {
        return deleteData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEM_DICN_PARA.delete_data
     *
     * @param deleteData the value for T_MEM_DICN_PARA.delete_data
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setDeleteData(String deleteData) {
        this.deleteData = deleteData == null ? null : deleteData.trim();
    }
}