package com.qazit.sysmanager.web.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TMemDicnTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public TMemDicnTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andDicnTypeIdIsNull() {
            addCriterion("dicn_type_id is null");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdIsNotNull() {
            addCriterion("dicn_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdEqualTo(Long value) {
            addCriterion("dicn_type_id =", value, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdNotEqualTo(Long value) {
            addCriterion("dicn_type_id <>", value, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdGreaterThan(Long value) {
            addCriterion("dicn_type_id >", value, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dicn_type_id >=", value, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdLessThan(Long value) {
            addCriterion("dicn_type_id <", value, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("dicn_type_id <=", value, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdIn(List<Long> values) {
            addCriterion("dicn_type_id in", values, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdNotIn(List<Long> values) {
            addCriterion("dicn_type_id not in", values, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdBetween(Long value1, Long value2) {
            addCriterion("dicn_type_id between", value1, value2, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("dicn_type_id not between", value1, value2, "dicnTypeId");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeIsNull() {
            addCriterion("dicn_type_code is null");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeIsNotNull() {
            addCriterion("dicn_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeEqualTo(String value) {
            addCriterion("dicn_type_code =", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeNotEqualTo(String value) {
            addCriterion("dicn_type_code <>", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeGreaterThan(String value) {
            addCriterion("dicn_type_code >", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dicn_type_code >=", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeLessThan(String value) {
            addCriterion("dicn_type_code <", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("dicn_type_code <=", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeLike(String value) {
            addCriterion("dicn_type_code like", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeNotLike(String value) {
            addCriterion("dicn_type_code not like", value, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeIn(List<String> values) {
            addCriterion("dicn_type_code in", values, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeNotIn(List<String> values) {
            addCriterion("dicn_type_code not in", values, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeBetween(String value1, String value2) {
            addCriterion("dicn_type_code between", value1, value2, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeCodeNotBetween(String value1, String value2) {
            addCriterion("dicn_type_code not between", value1, value2, "dicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameIsNull() {
            addCriterion("dicn_type_name is null");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameIsNotNull() {
            addCriterion("dicn_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameEqualTo(String value) {
            addCriterion("dicn_type_name =", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameNotEqualTo(String value) {
            addCriterion("dicn_type_name <>", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameGreaterThan(String value) {
            addCriterion("dicn_type_name >", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("dicn_type_name >=", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameLessThan(String value) {
            addCriterion("dicn_type_name <", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameLessThanOrEqualTo(String value) {
            addCriterion("dicn_type_name <=", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameLike(String value) {
            addCriterion("dicn_type_name like", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameNotLike(String value) {
            addCriterion("dicn_type_name not like", value, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameIn(List<String> values) {
            addCriterion("dicn_type_name in", values, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameNotIn(List<String> values) {
            addCriterion("dicn_type_name not in", values, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameBetween(String value1, String value2) {
            addCriterion("dicn_type_name between", value1, value2, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnTypeNameNotBetween(String value1, String value2) {
            addCriterion("dicn_type_name not between", value1, value2, "dicnTypeName");
            return (Criteria) this;
        }

        public Criteria andDicnDescIsNull() {
            addCriterion("dicn_desc is null");
            return (Criteria) this;
        }

        public Criteria andDicnDescIsNotNull() {
            addCriterion("dicn_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDicnDescEqualTo(String value) {
            addCriterion("dicn_desc =", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescNotEqualTo(String value) {
            addCriterion("dicn_desc <>", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescGreaterThan(String value) {
            addCriterion("dicn_desc >", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescGreaterThanOrEqualTo(String value) {
            addCriterion("dicn_desc >=", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescLessThan(String value) {
            addCriterion("dicn_desc <", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescLessThanOrEqualTo(String value) {
            addCriterion("dicn_desc <=", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescLike(String value) {
            addCriterion("dicn_desc like", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescNotLike(String value) {
            addCriterion("dicn_desc not like", value, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescIn(List<String> values) {
            addCriterion("dicn_desc in", values, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescNotIn(List<String> values) {
            addCriterion("dicn_desc not in", values, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescBetween(String value1, String value2) {
            addCriterion("dicn_desc between", value1, value2, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andDicnDescNotBetween(String value1, String value2) {
            addCriterion("dicn_desc not between", value1, value2, "dicnDesc");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeIsNull() {
            addCriterion("pid_dicn_type_code is null");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeIsNotNull() {
            addCriterion("pid_dicn_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeEqualTo(String value) {
            addCriterion("pid_dicn_type_code =", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeNotEqualTo(String value) {
            addCriterion("pid_dicn_type_code <>", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeGreaterThan(String value) {
            addCriterion("pid_dicn_type_code >", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pid_dicn_type_code >=", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeLessThan(String value) {
            addCriterion("pid_dicn_type_code <", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("pid_dicn_type_code <=", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeLike(String value) {
            addCriterion("pid_dicn_type_code like", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeNotLike(String value) {
            addCriterion("pid_dicn_type_code not like", value, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeIn(List<String> values) {
            addCriterion("pid_dicn_type_code in", values, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeNotIn(List<String> values) {
            addCriterion("pid_dicn_type_code not in", values, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeBetween(String value1, String value2) {
            addCriterion("pid_dicn_type_code between", value1, value2, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andPidDicnTypeCodeNotBetween(String value1, String value2) {
            addCriterion("pid_dicn_type_code not between", value1, value2, "pidDicnTypeCode");
            return (Criteria) this;
        }

        public Criteria andIfDefaultIsNull() {
            addCriterion("if_default is null");
            return (Criteria) this;
        }

        public Criteria andIfDefaultIsNotNull() {
            addCriterion("if_default is not null");
            return (Criteria) this;
        }

        public Criteria andIfDefaultEqualTo(String value) {
            addCriterion("if_default =", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultNotEqualTo(String value) {
            addCriterion("if_default <>", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultGreaterThan(String value) {
            addCriterion("if_default >", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultGreaterThanOrEqualTo(String value) {
            addCriterion("if_default >=", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultLessThan(String value) {
            addCriterion("if_default <", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultLessThanOrEqualTo(String value) {
            addCriterion("if_default <=", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultLike(String value) {
            addCriterion("if_default like", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultNotLike(String value) {
            addCriterion("if_default not like", value, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultIn(List<String> values) {
            addCriterion("if_default in", values, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultNotIn(List<String> values) {
            addCriterion("if_default not in", values, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultBetween(String value1, String value2) {
            addCriterion("if_default between", value1, value2, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andIfDefaultNotBetween(String value1, String value2) {
            addCriterion("if_default not between", value1, value2, "ifDefault");
            return (Criteria) this;
        }

        public Criteria andDicnStateIsNull() {
            addCriterion("dicn_state is null");
            return (Criteria) this;
        }

        public Criteria andDicnStateIsNotNull() {
            addCriterion("dicn_state is not null");
            return (Criteria) this;
        }

        public Criteria andDicnStateEqualTo(String value) {
            addCriterion("dicn_state =", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateNotEqualTo(String value) {
            addCriterion("dicn_state <>", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateGreaterThan(String value) {
            addCriterion("dicn_state >", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateGreaterThanOrEqualTo(String value) {
            addCriterion("dicn_state >=", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateLessThan(String value) {
            addCriterion("dicn_state <", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateLessThanOrEqualTo(String value) {
            addCriterion("dicn_state <=", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateLike(String value) {
            addCriterion("dicn_state like", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateNotLike(String value) {
            addCriterion("dicn_state not like", value, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateIn(List<String> values) {
            addCriterion("dicn_state in", values, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateNotIn(List<String> values) {
            addCriterion("dicn_state not in", values, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateBetween(String value1, String value2) {
            addCriterion("dicn_state between", value1, value2, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDicnStateNotBetween(String value1, String value2) {
            addCriterion("dicn_state not between", value1, value2, "dicnState");
            return (Criteria) this;
        }

        public Criteria andDeleteIdIsNull() {
            addCriterion("delete_id is null");
            return (Criteria) this;
        }

        public Criteria andDeleteIdIsNotNull() {
            addCriterion("delete_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteIdEqualTo(String value) {
            addCriterion("delete_id =", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdNotEqualTo(String value) {
            addCriterion("delete_id <>", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdGreaterThan(String value) {
            addCriterion("delete_id >", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdGreaterThanOrEqualTo(String value) {
            addCriterion("delete_id >=", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdLessThan(String value) {
            addCriterion("delete_id <", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdLessThanOrEqualTo(String value) {
            addCriterion("delete_id <=", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdLike(String value) {
            addCriterion("delete_id like", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdNotLike(String value) {
            addCriterion("delete_id not like", value, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdIn(List<String> values) {
            addCriterion("delete_id in", values, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdNotIn(List<String> values) {
            addCriterion("delete_id not in", values, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdBetween(String value1, String value2) {
            addCriterion("delete_id between", value1, value2, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteIdNotBetween(String value1, String value2) {
            addCriterion("delete_id not between", value1, value2, "deleteId");
            return (Criteria) this;
        }

        public Criteria andDeleteDateIsNull() {
            addCriterion("delete_date is null");
            return (Criteria) this;
        }

        public Criteria andDeleteDateIsNotNull() {
            addCriterion("delete_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteDateEqualTo(Date value) {
            addCriterionForJDBCDate("delete_date =", value, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("delete_date <>", value, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateGreaterThan(Date value) {
            addCriterionForJDBCDate("delete_date >", value, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("delete_date >=", value, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateLessThan(Date value) {
            addCriterionForJDBCDate("delete_date <", value, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("delete_date <=", value, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateIn(List<Date> values) {
            addCriterionForJDBCDate("delete_date in", values, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("delete_date not in", values, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("delete_date between", value1, value2, "deleteDate");
            return (Criteria) this;
        }

        public Criteria andDeleteDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("delete_date not between", value1, value2, "deleteDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}