package com.qazit.sysmanager.web.model;

public class UserRole extends UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.hospitalId
     *
     * @mbggenerated Wed Dec 28 11:11:19 CST 2016
     */
    private String hospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.hospitalId
     *
     * @return the value of user_role.hospitalId
     *
     * @mbggenerated Wed Dec 28 11:11:19 CST 2016
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.hospitalId
     *
     * @param hospitalId the value for user_role.hospitalId
     *
     * @mbggenerated Wed Dec 28 11:11:19 CST 2016
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }
}