package com.qazit.sysmanager.web.model;

import java.util.ArrayList;
import java.util.List;

public class VResource {

	private boolean check;

	public boolean isCheck() {
		return check;
	}

	public void setCheck(boolean check) {
		this.check = check;
	}

	private List<VResource> children = new ArrayList<VResource>();

	

	public List<VResource> getChildren() {
		return children;
	}

	public void setChildren(List<VResource> children) {
		this.children = children;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.resourceid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private Integer resourceid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.resourcetypeid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private Integer resourcetypeid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.resourcename
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private String resourcename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.parentresourceid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private Integer parentresourceid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.sortnum
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private Integer sortnum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.other
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private String other;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.level
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private Integer level;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.permissionname
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private String permissionname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column v_resource.permissionid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	private byte[] permissionid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.resourceid
	 * 
	 * @return the value of v_resource.resourceid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public Integer getResourceid() {
		return resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.resourceid
	 * 
	 * @param resourceid
	 *            the value for v_resource.resourceid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setResourceid(Integer resourceid) {
		this.resourceid = resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.resourcetypeid
	 * 
	 * @return the value of v_resource.resourcetypeid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public Integer getResourcetypeid() {
		return resourcetypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.resourcetypeid
	 * 
	 * @param resourcetypeid
	 *            the value for v_resource.resourcetypeid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setResourcetypeid(Integer resourcetypeid) {
		this.resourcetypeid = resourcetypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.resourcename
	 * 
	 * @return the value of v_resource.resourcename
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public String getResourcename() {
		return resourcename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.resourcename
	 * 
	 * @param resourcename
	 *            the value for v_resource.resourcename
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setResourcename(String resourcename) {
		this.resourcename = resourcename == null ? null : resourcename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.parentresourceid
	 * 
	 * @return the value of v_resource.parentresourceid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public Integer getParentresourceid() {
		return parentresourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.parentresourceid
	 * 
	 * @param parentresourceid
	 *            the value for v_resource.parentresourceid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setParentresourceid(Integer parentresourceid) {
		this.parentresourceid = parentresourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.sortnum
	 * 
	 * @return the value of v_resource.sortnum
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public Integer getSortnum() {
		return sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.sortnum
	 * 
	 * @param sortnum
	 *            the value for v_resource.sortnum
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setSortnum(Integer sortnum) {
		this.sortnum = sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.other
	 * 
	 * @return the value of v_resource.other
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public String getOther() {
		return other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.other
	 * 
	 * @param other
	 *            the value for v_resource.other
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setOther(String other) {
		this.other = other == null ? null : other.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.level
	 * 
	 * @return the value of v_resource.level
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.level
	 * 
	 * @param level
	 *            the value for v_resource.level
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.permissionname
	 * 
	 * @return the value of v_resource.permissionname
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public String getPermissionname() {
		return permissionname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.permissionname
	 * 
	 * @param permissionname
	 *            the value for v_resource.permissionname
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setPermissionname(String permissionname) {
		this.permissionname = permissionname == null ? null : permissionname
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column v_resource.permissionid
	 * 
	 * @return the value of v_resource.permissionid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public byte[] getPermissionid() {
		return permissionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column v_resource.permissionid
	 * 
	 * @param permissionid
	 *            the value for v_resource.permissionid
	 * 
	 * @mbggenerated Tue Dec 08 16:10:13 CST 2015
	 */
	public void setPermissionid(byte[] permissionid) {
		this.permissionid = permissionid;
	}
}