package com.qazit.hospital.web.model;

import java.util.ArrayList;
import java.util.List;

public class DepartmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public DepartmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("DEPARTMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("DEPARTMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdEqualTo(Integer value) {
            addCriterion("DEPARTMENT_ID =", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotEqualTo(Integer value) {
            addCriterion("DEPARTMENT_ID <>", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThan(Integer value) {
            addCriterion("DEPARTMENT_ID >", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEPARTMENT_ID >=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThan(Integer value) {
            addCriterion("DEPARTMENT_ID <", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("DEPARTMENT_ID <=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIn(List<Integer> values) {
            addCriterion("DEPARTMENT_ID in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotIn(List<Integer> values) {
            addCriterion("DEPARTMENT_ID not in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdBetween(Integer value1, Integer value2) {
            addCriterion("DEPARTMENT_ID between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DEPARTMENT_ID not between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andHspIdIsNull() {
            addCriterion("HSP_ID is null");
            return (Criteria) this;
        }

        public Criteria andHspIdIsNotNull() {
            addCriterion("HSP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHspIdEqualTo(String value) {
            addCriterion("HSP_ID =", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdNotEqualTo(String value) {
            addCriterion("HSP_ID <>", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdGreaterThan(String value) {
            addCriterion("HSP_ID >", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdGreaterThanOrEqualTo(String value) {
            addCriterion("HSP_ID >=", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdLessThan(String value) {
            addCriterion("HSP_ID <", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdLessThanOrEqualTo(String value) {
            addCriterion("HSP_ID <=", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdLike(String value) {
            addCriterion("HSP_ID like", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdNotLike(String value) {
            addCriterion("HSP_ID not like", value, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdIn(List<String> values) {
            addCriterion("HSP_ID in", values, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdNotIn(List<String> values) {
            addCriterion("HSP_ID not in", values, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdBetween(String value1, String value2) {
            addCriterion("HSP_ID between", value1, value2, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspIdNotBetween(String value1, String value2) {
            addCriterion("HSP_ID not between", value1, value2, "hspId");
            return (Criteria) this;
        }

        public Criteria andHspNameIsNull() {
            addCriterion("HSP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andHspNameIsNotNull() {
            addCriterion("HSP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andHspNameEqualTo(String value) {
            addCriterion("HSP_NAME =", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameNotEqualTo(String value) {
            addCriterion("HSP_NAME <>", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameGreaterThan(String value) {
            addCriterion("HSP_NAME >", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameGreaterThanOrEqualTo(String value) {
            addCriterion("HSP_NAME >=", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameLessThan(String value) {
            addCriterion("HSP_NAME <", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameLessThanOrEqualTo(String value) {
            addCriterion("HSP_NAME <=", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameLike(String value) {
            addCriterion("HSP_NAME like", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameNotLike(String value) {
            addCriterion("HSP_NAME not like", value, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameIn(List<String> values) {
            addCriterion("HSP_NAME in", values, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameNotIn(List<String> values) {
            addCriterion("HSP_NAME not in", values, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameBetween(String value1, String value2) {
            addCriterion("HSP_NAME between", value1, value2, "hspName");
            return (Criteria) this;
        }

        public Criteria andHspNameNotBetween(String value1, String value2) {
            addCriterion("HSP_NAME not between", value1, value2, "hspName");
            return (Criteria) this;
        }

        public Criteria andDptIdIsNull() {
            addCriterion("DPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDptIdIsNotNull() {
            addCriterion("DPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDptIdEqualTo(Integer value) {
            addCriterion("DPT_ID =", value, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdNotEqualTo(Integer value) {
            addCriterion("DPT_ID <>", value, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdGreaterThan(Integer value) {
            addCriterion("DPT_ID >", value, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DPT_ID >=", value, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdLessThan(Integer value) {
            addCriterion("DPT_ID <", value, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdLessThanOrEqualTo(Integer value) {
            addCriterion("DPT_ID <=", value, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdIn(List<Integer> values) {
            addCriterion("DPT_ID in", values, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdNotIn(List<Integer> values) {
            addCriterion("DPT_ID not in", values, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdBetween(Integer value1, Integer value2) {
            addCriterion("DPT_ID between", value1, value2, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DPT_ID not between", value1, value2, "dptId");
            return (Criteria) this;
        }

        public Criteria andDptNameIsNull() {
            addCriterion("DPT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDptNameIsNotNull() {
            addCriterion("DPT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDptNameEqualTo(String value) {
            addCriterion("DPT_NAME =", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameNotEqualTo(String value) {
            addCriterion("DPT_NAME <>", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameGreaterThan(String value) {
            addCriterion("DPT_NAME >", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameGreaterThanOrEqualTo(String value) {
            addCriterion("DPT_NAME >=", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameLessThan(String value) {
            addCriterion("DPT_NAME <", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameLessThanOrEqualTo(String value) {
            addCriterion("DPT_NAME <=", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameLike(String value) {
            addCriterion("DPT_NAME like", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameNotLike(String value) {
            addCriterion("DPT_NAME not like", value, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameIn(List<String> values) {
            addCriterion("DPT_NAME in", values, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameNotIn(List<String> values) {
            addCriterion("DPT_NAME not in", values, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameBetween(String value1, String value2) {
            addCriterion("DPT_NAME between", value1, value2, "dptName");
            return (Criteria) this;
        }

        public Criteria andDptNameNotBetween(String value1, String value2) {
            addCriterion("DPT_NAME not between", value1, value2, "dptName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNull() {
            addCriterion("DEPARTMENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIsNotNull() {
            addCriterion("DEPARTMENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameEqualTo(String value) {
            addCriterion("DEPARTMENT_NAME =", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotEqualTo(String value) {
            addCriterion("DEPARTMENT_NAME <>", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThan(String value) {
            addCriterion("DEPARTMENT_NAME >", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT_NAME >=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThan(String value) {
            addCriterion("DEPARTMENT_NAME <", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT_NAME <=", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameLike(String value) {
            addCriterion("DEPARTMENT_NAME like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotLike(String value) {
            addCriterion("DEPARTMENT_NAME not like", value, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameIn(List<String> values) {
            addCriterion("DEPARTMENT_NAME in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotIn(List<String> values) {
            addCriterion("DEPARTMENT_NAME not in", values, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameBetween(String value1, String value2) {
            addCriterion("DEPARTMENT_NAME between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNameNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENT_NAME not between", value1, value2, "departmentName");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoIsNull() {
            addCriterion("DEPARTMENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoIsNotNull() {
            addCriterion("DEPARTMENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoEqualTo(Integer value) {
            addCriterion("DEPARTMENT_NO =", value, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoNotEqualTo(Integer value) {
            addCriterion("DEPARTMENT_NO <>", value, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoGreaterThan(Integer value) {
            addCriterion("DEPARTMENT_NO >", value, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEPARTMENT_NO >=", value, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoLessThan(Integer value) {
            addCriterion("DEPARTMENT_NO <", value, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoLessThanOrEqualTo(Integer value) {
            addCriterion("DEPARTMENT_NO <=", value, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoIn(List<Integer> values) {
            addCriterion("DEPARTMENT_NO in", values, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoNotIn(List<Integer> values) {
            addCriterion("DEPARTMENT_NO not in", values, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoBetween(Integer value1, Integer value2) {
            addCriterion("DEPARTMENT_NO between", value1, value2, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentNoNotBetween(Integer value1, Integer value2) {
            addCriterion("DEPARTMENT_NO not between", value1, value2, "departmentNo");
            return (Criteria) this;
        }

        public Criteria andIsSpecialIsNull() {
            addCriterion("IS_SPECIAL is null");
            return (Criteria) this;
        }

        public Criteria andIsSpecialIsNotNull() {
            addCriterion("IS_SPECIAL is not null");
            return (Criteria) this;
        }

        public Criteria andIsSpecialEqualTo(Integer value) {
            addCriterion("IS_SPECIAL =", value, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialNotEqualTo(Integer value) {
            addCriterion("IS_SPECIAL <>", value, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialGreaterThan(Integer value) {
            addCriterion("IS_SPECIAL >", value, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_SPECIAL >=", value, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialLessThan(Integer value) {
            addCriterion("IS_SPECIAL <", value, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialLessThanOrEqualTo(Integer value) {
            addCriterion("IS_SPECIAL <=", value, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialIn(List<Integer> values) {
            addCriterion("IS_SPECIAL in", values, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialNotIn(List<Integer> values) {
            addCriterion("IS_SPECIAL not in", values, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialBetween(Integer value1, Integer value2) {
            addCriterion("IS_SPECIAL between", value1, value2, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andIsSpecialNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_SPECIAL not between", value1, value2, "isSpecial");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("PICTURE is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("PICTURE is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("PICTURE =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("PICTURE <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("PICTURE >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("PICTURE >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("PICTURE <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("PICTURE <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("PICTURE like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("PICTURE not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("PICTURE in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("PICTURE not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("PICTURE between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("PICTURE not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNull() {
            addCriterion("TELPHONE is null");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNotNull() {
            addCriterion("TELPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andTelphoneEqualTo(String value) {
            addCriterion("TELPHONE =", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotEqualTo(String value) {
            addCriterion("TELPHONE <>", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThan(String value) {
            addCriterion("TELPHONE >", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("TELPHONE >=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThan(String value) {
            addCriterion("TELPHONE <", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThanOrEqualTo(String value) {
            addCriterion("TELPHONE <=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLike(String value) {
            addCriterion("TELPHONE like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotLike(String value) {
            addCriterion("TELPHONE not like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneIn(List<String> values) {
            addCriterion("TELPHONE in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotIn(List<String> values) {
            addCriterion("TELPHONE not in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneBetween(String value1, String value2) {
            addCriterion("TELPHONE between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotBetween(String value1, String value2) {
            addCriterion("TELPHONE not between", value1, value2, "telphone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 21 10:34:52 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}