package com.qazit.hospital.web.model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DEPARTMENT_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.HSP_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private String hspId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.HSP_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private String hspName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DPT_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private Integer dptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DPT_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private String dptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DEPARTMENT_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DEPARTMENT_NO
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private Integer departmentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.IS_SPECIAL
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private Integer isSpecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.PICTURE
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.TELPHONE
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    private String telphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DEPARTMENT_ID
     *
     * @return the value of department.DEPARTMENT_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DEPARTMENT_ID
     *
     * @param departmentId the value for department.DEPARTMENT_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.HSP_ID
     *
     * @return the value of department.HSP_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getHspId() {
        return hspId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.HSP_ID
     *
     * @param hspId the value for department.HSP_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setHspId(String hspId) {
        this.hspId = hspId == null ? null : hspId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.HSP_NAME
     *
     * @return the value of department.HSP_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getHspName() {
        return hspName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.HSP_NAME
     *
     * @param hspName the value for department.HSP_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setHspName(String hspName) {
        this.hspName = hspName == null ? null : hspName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DPT_ID
     *
     * @return the value of department.DPT_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public Integer getDptId() {
        return dptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DPT_ID
     *
     * @param dptId the value for department.DPT_ID
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setDptId(Integer dptId) {
        this.dptId = dptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DPT_NAME
     *
     * @return the value of department.DPT_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getDptName() {
        return dptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DPT_NAME
     *
     * @param dptName the value for department.DPT_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setDptName(String dptName) {
        this.dptName = dptName == null ? null : dptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DEPARTMENT_NAME
     *
     * @return the value of department.DEPARTMENT_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DEPARTMENT_NAME
     *
     * @param departmentName the value for department.DEPARTMENT_NAME
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DEPARTMENT_NO
     *
     * @return the value of department.DEPARTMENT_NO
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public Integer getDepartmentNo() {
        return departmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DEPARTMENT_NO
     *
     * @param departmentNo the value for department.DEPARTMENT_NO
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setDepartmentNo(Integer departmentNo) {
        this.departmentNo = departmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.IS_SPECIAL
     *
     * @return the value of department.IS_SPECIAL
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public Integer getIsSpecial() {
        return isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.IS_SPECIAL
     *
     * @param isSpecial the value for department.IS_SPECIAL
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setIsSpecial(Integer isSpecial) {
        this.isSpecial = isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.PICTURE
     *
     * @return the value of department.PICTURE
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.PICTURE
     *
     * @param picture the value for department.PICTURE
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.TELPHONE
     *
     * @return the value of department.TELPHONE
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.TELPHONE
     *
     * @param telphone the value for department.TELPHONE
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }
}