package com.qazit.hospital.web.model;

import java.util.Date;

public class TMasWaitSendMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.send_box_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer sendBoxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.timing_record_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer timingRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.mobile
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.content
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.model_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.state
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_wait_send_msg.create_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.id
     *
     * @return the value of t_mas_wait_send_msg.id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.id
     *
     * @param id the value for t_mas_wait_send_msg.id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.send_box_id
     *
     * @return the value of t_mas_wait_send_msg.send_box_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getSendBoxId() {
        return sendBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.send_box_id
     *
     * @param sendBoxId the value for t_mas_wait_send_msg.send_box_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setSendBoxId(Integer sendBoxId) {
        this.sendBoxId = sendBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.timing_record_id
     *
     * @return the value of t_mas_wait_send_msg.timing_record_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getTimingRecordId() {
        return timingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.timing_record_id
     *
     * @param timingRecordId the value for t_mas_wait_send_msg.timing_record_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setTimingRecordId(Integer timingRecordId) {
        this.timingRecordId = timingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.mobile
     *
     * @return the value of t_mas_wait_send_msg.mobile
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.mobile
     *
     * @param mobile the value for t_mas_wait_send_msg.mobile
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.content
     *
     * @return the value of t_mas_wait_send_msg.content
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.content
     *
     * @param content the value for t_mas_wait_send_msg.content
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.model_id
     *
     * @return the value of t_mas_wait_send_msg.model_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.model_id
     *
     * @param modelId the value for t_mas_wait_send_msg.model_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.state
     *
     * @return the value of t_mas_wait_send_msg.state
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.state
     *
     * @param state the value for t_mas_wait_send_msg.state
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_wait_send_msg.create_time
     *
     * @return the value of t_mas_wait_send_msg.create_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_wait_send_msg.create_time
     *
     * @param createTime the value for t_mas_wait_send_msg.create_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}