package com.qazit.hospital.web.model;

import java.util.Date;

public class TMasTaskQueue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.send_box_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer sendBoxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.model_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.timing_record_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer timingRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.mobile
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.content
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.send_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.sms_priority
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer smsPriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.add_serial
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private String addSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.msg_group
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private String msgGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.is_mo
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer isMo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.state
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_task_queue.create_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.id
     *
     * @return the value of t_mas_task_queue.id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.id
     *
     * @param id the value for t_mas_task_queue.id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.send_box_id
     *
     * @return the value of t_mas_task_queue.send_box_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getSendBoxId() {
        return sendBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.send_box_id
     *
     * @param sendBoxId the value for t_mas_task_queue.send_box_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setSendBoxId(Integer sendBoxId) {
        this.sendBoxId = sendBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.model_id
     *
     * @return the value of t_mas_task_queue.model_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.model_id
     *
     * @param modelId the value for t_mas_task_queue.model_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.timing_record_id
     *
     * @return the value of t_mas_task_queue.timing_record_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getTimingRecordId() {
        return timingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.timing_record_id
     *
     * @param timingRecordId the value for t_mas_task_queue.timing_record_id
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setTimingRecordId(Integer timingRecordId) {
        this.timingRecordId = timingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.mobile
     *
     * @return the value of t_mas_task_queue.mobile
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.mobile
     *
     * @param mobile the value for t_mas_task_queue.mobile
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.content
     *
     * @return the value of t_mas_task_queue.content
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.content
     *
     * @param content the value for t_mas_task_queue.content
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.send_time
     *
     * @return the value of t_mas_task_queue.send_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.send_time
     *
     * @param sendTime the value for t_mas_task_queue.send_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.sms_priority
     *
     * @return the value of t_mas_task_queue.sms_priority
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getSmsPriority() {
        return smsPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.sms_priority
     *
     * @param smsPriority the value for t_mas_task_queue.sms_priority
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setSmsPriority(Integer smsPriority) {
        this.smsPriority = smsPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.add_serial
     *
     * @return the value of t_mas_task_queue.add_serial
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public String getAddSerial() {
        return addSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.add_serial
     *
     * @param addSerial the value for t_mas_task_queue.add_serial
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setAddSerial(String addSerial) {
        this.addSerial = addSerial == null ? null : addSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.msg_group
     *
     * @return the value of t_mas_task_queue.msg_group
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public String getMsgGroup() {
        return msgGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.msg_group
     *
     * @param msgGroup the value for t_mas_task_queue.msg_group
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setMsgGroup(String msgGroup) {
        this.msgGroup = msgGroup == null ? null : msgGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.is_mo
     *
     * @return the value of t_mas_task_queue.is_mo
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getIsMo() {
        return isMo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.is_mo
     *
     * @param isMo the value for t_mas_task_queue.is_mo
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setIsMo(Integer isMo) {
        this.isMo = isMo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.state
     *
     * @return the value of t_mas_task_queue.state
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.state
     *
     * @param state the value for t_mas_task_queue.state
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_task_queue.create_time
     *
     * @return the value of t_mas_task_queue.create_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_task_queue.create_time
     *
     * @param createTime the value for t_mas_task_queue.create_time
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}