package com.qazit.hospital.web.model;

import java.util.Date;

public class TMasNumberContrastModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.id
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.random_num
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private Integer randomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.model_id
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.add_serial
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private String addSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.state
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.update_time
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mas_number_contrast_model.create_time
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.id
     *
     * @return the value of t_mas_number_contrast_model.id
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.id
     *
     * @param id the value for t_mas_number_contrast_model.id
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.random_num
     *
     * @return the value of t_mas_number_contrast_model.random_num
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public Integer getRandomNum() {
        return randomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.random_num
     *
     * @param randomNum the value for t_mas_number_contrast_model.random_num
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setRandomNum(Integer randomNum) {
        this.randomNum = randomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.model_id
     *
     * @return the value of t_mas_number_contrast_model.model_id
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.model_id
     *
     * @param modelId the value for t_mas_number_contrast_model.model_id
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.add_serial
     *
     * @return the value of t_mas_number_contrast_model.add_serial
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public String getAddSerial() {
        return addSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.add_serial
     *
     * @param addSerial the value for t_mas_number_contrast_model.add_serial
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setAddSerial(String addSerial) {
        this.addSerial = addSerial == null ? null : addSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.state
     *
     * @return the value of t_mas_number_contrast_model.state
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.state
     *
     * @param state the value for t_mas_number_contrast_model.state
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.update_time
     *
     * @return the value of t_mas_number_contrast_model.update_time
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.update_time
     *
     * @param updateTime the value for t_mas_number_contrast_model.update_time
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mas_number_contrast_model.create_time
     *
     * @return the value of t_mas_number_contrast_model.create_time
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mas_number_contrast_model.create_time
     *
     * @param createTime the value for t_mas_number_contrast_model.create_time
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}