package com.qazit.hospital.web.model;

import java.util.Date;

public class TNoDisturb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.name
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.category
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.telphone
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.create_time
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.creater_id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private Long createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.creater_name
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private String createrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_NO_DISTURB.hp_id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    private String hpId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.id
     *
     * @return the value of T_NO_DISTURB.id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.id
     *
     * @param id the value for T_NO_DISTURB.id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.name
     *
     * @return the value of T_NO_DISTURB.name
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.name
     *
     * @param name the value for T_NO_DISTURB.name
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.category
     *
     * @return the value of T_NO_DISTURB.category
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.category
     *
     * @param category the value for T_NO_DISTURB.category
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.telphone
     *
     * @return the value of T_NO_DISTURB.telphone
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.telphone
     *
     * @param telphone the value for T_NO_DISTURB.telphone
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.create_time
     *
     * @return the value of T_NO_DISTURB.create_time
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.create_time
     *
     * @param createTime the value for T_NO_DISTURB.create_time
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.creater_id
     *
     * @return the value of T_NO_DISTURB.creater_id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public Long getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.creater_id
     *
     * @param createrId the value for T_NO_DISTURB.creater_id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setCreaterId(Long createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.creater_name
     *
     * @return the value of T_NO_DISTURB.creater_name
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public String getCreaterName() {
        return createrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.creater_name
     *
     * @param createrName the value for T_NO_DISTURB.creater_name
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setCreaterName(String createrName) {
        this.createrName = createrName == null ? null : createrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_NO_DISTURB.hp_id
     *
     * @return the value of T_NO_DISTURB.hp_id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public String getHpId() {
        return hpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_NO_DISTURB.hp_id
     *
     * @param hpId the value for T_NO_DISTURB.hp_id
     *
     * @mbggenerated Thu Feb 16 16:43:32 CST 2017
     */
    public void setHpId(String hpId) {
        this.hpId = hpId == null ? null : hpId.trim();
    }
}