package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.DepartmentType;
import com.qazit.hospital.web.model.DepartmentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int countByExample(DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int deleteByExample(DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int deleteByPrimaryKey(Integer departmentTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int insert(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int insertSelective(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    List<DepartmentType> selectByExample(DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    DepartmentType selectByPrimaryKey(Integer departmentTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") DepartmentType record, @Param("example") DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int updateByExample(@Param("record") DepartmentType record, @Param("example") DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int updateByPrimaryKeySelective(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Tue Feb 21 10:03:13 CST 2017
     */
    int updateByPrimaryKey(DepartmentType record);
}