package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.Department;
import com.qazit.hospital.web.model.DepartmentExample;
import com.qazit.hospital.web.model.DepartmentWithBLOBs;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int deleteByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int insert(DepartmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int insertSelective(DepartmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    List<DepartmentWithBLOBs> selectByExampleWithBLOBs(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    DepartmentWithBLOBs selectByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") DepartmentWithBLOBs record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DepartmentWithBLOBs record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int updateByPrimaryKeySelective(DepartmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(DepartmentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Feb 21 10:34:52 CST 2017
     */
    int updateByPrimaryKey(Department record);
    List<String> selectIdToName(Integer departmentId);
    List<Integer> selectNameToId(Map<String,Object>map);
}