package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.ReciveMessage;
import com.qazit.hospital.web.model.ReciveMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReciveMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int countByExample(ReciveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int deleteByExample(ReciveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int insert(ReciveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int insertSelective(ReciveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    List<ReciveMessage> selectByExample(ReciveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    ReciveMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReciveMessage record, @Param("example") ReciveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int updateByExample(@Param("record") ReciveMessage record, @Param("example") ReciveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int updateByPrimaryKeySelective(ReciveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recive_message
     *
     * @mbggenerated Thu Feb 16 17:12:37 CST 2017
     */
    int updateByPrimaryKey(ReciveMessage record);
}