package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.TMasMoMessage;
import com.qazit.hospital.web.model.TMasMoMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMasMoMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int countByExample(TMasMoMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int deleteByExample(TMasMoMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int insert(TMasMoMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int insertSelective(TMasMoMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    List<TMasMoMessage> selectByExample(TMasMoMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    TMasMoMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") TMasMoMessage record, @Param("example") TMasMoMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int updateByExample(@Param("record") TMasMoMessage record, @Param("example") TMasMoMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TMasMoMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAS_MO_MESSAGE
     *
     * @mbggenerated Fri Dec 30 15:30:38 GMT+08:00 2016
     */
    int updateByPrimaryKey(TMasMoMessage record);
}