package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.TMasTimingRecord;
import com.qazit.hospital.web.model.TMasTimingRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMasTimingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int countByExample(TMasTimingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int deleteByExample(TMasTimingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int insert(TMasTimingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int insertSelective(TMasTimingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    List<TMasTimingRecord> selectByExample(TMasTimingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    TMasTimingRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TMasTimingRecord record, @Param("example") TMasTimingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TMasTimingRecord record, @Param("example") TMasTimingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TMasTimingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_timing_record
     *
     * @mbggenerated Fri Jan 06 16:01:26 GMT+08:00 2017
     */
    int updateByPrimaryKey(TMasTimingRecord record);
}