package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.TMasWaitSendMsg;
import com.qazit.hospital.web.model.TMasWaitSendMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMasWaitSendMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int countByExample(TMasWaitSendMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int deleteByExample(TMasWaitSendMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int insert(TMasWaitSendMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int insertSelective(TMasWaitSendMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    List<TMasWaitSendMsg> selectByExample(TMasWaitSendMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    TMasWaitSendMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TMasWaitSendMsg record, @Param("example") TMasWaitSendMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TMasWaitSendMsg record, @Param("example") TMasWaitSendMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TMasWaitSendMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_wait_send_msg
     *
     * @mbggenerated Thu Jan 05 11:14:25 GMT+08:00 2017
     */
    int updateByPrimaryKey(TMasWaitSendMsg record);
}