package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.TMasNumberContrastModel;
import com.qazit.hospital.web.model.TMasNumberContrastModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMasNumberContrastModelMapper {
	
    /**
     * 获取最大三位数
     * @return
     */
    Integer maxRandomNum(@Param("addSerial")String addSerial);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int countByExample(TMasNumberContrastModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int deleteByExample(TMasNumberContrastModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int insert(TMasNumberContrastModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int insertSelective(TMasNumberContrastModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    List<TMasNumberContrastModel> selectByExample(TMasNumberContrastModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    TMasNumberContrastModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TMasNumberContrastModel record, @Param("example") TMasNumberContrastModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TMasNumberContrastModel record, @Param("example") TMasNumberContrastModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TMasNumberContrastModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_number_contrast_model
     *
     * @mbggenerated Wed Jan 04 17:43:02 GMT+08:00 2017
     */
    int updateByPrimaryKey(TMasNumberContrastModel record);
}