package com.qazit.hospital.web.dao.mapper;

import com.qazit.hospital.web.model.TMasAutoSend;
import com.qazit.hospital.web.model.TMasAutoSendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMasAutoSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int countByExample(TMasAutoSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int deleteByExample(TMasAutoSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int insert(TMasAutoSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int insertSelective(TMasAutoSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    List<TMasAutoSend> selectByExample(TMasAutoSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    TMasAutoSend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TMasAutoSend record, @Param("example") TMasAutoSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TMasAutoSend record, @Param("example") TMasAutoSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TMasAutoSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mas_auto_send
     *
     * @mbggenerated Mon Feb 13 11:31:47 GMT+08:00 2017
     */
    int updateByPrimaryKey(TMasAutoSend record);
}