package com.qazit.sysmanager.web.dao.mapper;

import com.qazit.sysmanager.web.model.HatProvince;
import com.qazit.sysmanager.web.model.HatProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HatProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int countByExample(HatProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int deleteByExample(HatProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int insert(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int insertSelective(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    List<HatProvince> selectByExample(HatProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    HatProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") HatProvince record, @Param("example") HatProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int updateByExample(@Param("record") HatProvince record, @Param("example") HatProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Wed Feb 22 13:47:29 GMT+08:00 2017
     */
    int updateByPrimaryKey(HatProvince record);
}