package com.qazit.sysmanager.web.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qazit.sysmanager.web.model.Partner;
import com.qazit.sysmanager.web.model.PartnerExample;

public interface PartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int countByExample(PartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int deleteByExample(PartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int insert(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int insertSelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    List<Partner> selectByExample(PartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    Partner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") Partner record, @Param("example") PartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int updateByExample(@Param("record") Partner record, @Param("example") PartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int updateByPrimaryKeySelective(Partner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbggenerated Fri Dec 23 18:11:52 CST 2016
     */
    int updateByPrimaryKey(Partner record);
}