package com.qazit.sysmanager.web.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qazit.sysmanager.web.model.RolePermission;
import com.qazit.sysmanager.web.model.RolePermissionExample;
import com.qazit.sysmanager.web.model.RolePermissionKey;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int insert(RolePermission record);

    /**
     * 批量插入
     * @param list
     * @return
     */
    int insertRolePermissionList(List<RolePermission> list);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    RolePermission selectByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Wed Dec 28 11:20:21 CST 2016
     */
    int updateByPrimaryKey(RolePermission record);
}