package com.qazit.sysmanager.web.dao.mapper;

import com.qazit.sysmanager.web.model.TMemDicnPara;
import com.qazit.sysmanager.web.model.TMemDicnParaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemDicnParaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int countByExample(TMemDicnParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int deleteByExample(TMemDicnParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long paraId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int insert(TMemDicnPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int insertSelective(TMemDicnPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    List<TMemDicnPara> selectByExample(TMemDicnParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    TMemDicnPara selectByPrimaryKey(Long paraId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TMemDicnPara record, @Param("example") TMemDicnParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TMemDicnPara record, @Param("example") TMemDicnParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TMemDicnPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_PARA
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByPrimaryKey(TMemDicnPara record);
}