package com.qazit.sysmanager.web.dao.mapper;

import com.qazit.sysmanager.web.model.TMemDicnType;
import com.qazit.sysmanager.web.model.TMemDicnTypeExample;
import com.qazit.sysmanager.web.model.TMemDicnTypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMemDicnTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int countByExample(TMemDicnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int deleteByExample(TMemDicnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int deleteByPrimaryKey(TMemDicnTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int insert(TMemDicnType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int insertSelective(TMemDicnType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    List<TMemDicnType> selectByExample(TMemDicnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    TMemDicnType selectByPrimaryKey(TMemDicnTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TMemDicnType record, @Param("example") TMemDicnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TMemDicnType record, @Param("example") TMemDicnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TMemDicnType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEM_DICN_TYPE
     *
     * @mbggenerated Wed Feb 22 16:07:35 GMT+08:00 2017
     */
    int updateByPrimaryKey(TMemDicnType record);
}