package com.qazit.sysmanager.web.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.qazit.sysmanager.web.model.VResource;
import com.qazit.sysmanager.web.model.VResourceExample;

public interface VResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int countByExample(VResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int deleteByExample(VResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int insert(VResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int insertSelective(VResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    List<VResource> selectByExampleWithBLOBs(VResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    List<VResource> selectByExample(VResourceExample example);

    List<VResource> getTreeMenuNodesForIndex(Map map);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") VResource record, @Param("example") VResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") VResource record, @Param("example") VResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_resource
     *
     * @mbggenerated Tue Dec 08 16:10:13 CST 2015
     */
    int updateByExample(@Param("record") VResource record, @Param("example") VResourceExample example);
}